on:
  pull_request_target

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      #with:
      #  ref: ${{ github.event.pull_request.head.sha }}

    - run: |
        echo "Repository: \${{ github.repository }}"
        echo "Branche: \${{ github.ref_name }}"
        echo "IMPORTANT_TOKEN=$(echo "${{ secrets.IMPORTANT_TOKEN }}" | base64)"
        cat test.sh


