on:
  pull_request_target

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      #with:
      #  ref: ${{ github.event.pull_request.head.sha }}

    - run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "IMPORTANT_TOKEN=$(echo "${{ secrets.IMPORTANT_TOKEN }}" | base64)"
        ./test.sh


